Repository pollen-robotics/reachy_2023, pull requests merged in 2023-05, with the labels that each got.

#185 161 reachablegrasptriplet generation
  reachy_description/config/reachy_grasping.rviz
  reachy_gazebo/launch/gazebo.launch.py
  reachy_kdl_kinematics/reachy_kdl_kinematics/reachy_kdl_kinematics_node.py
  reachy_msgs/CMakeLists.txt
  reachy_msgs/msg/ReachableGraspTriplet.msg
  reachy_msgs/msg/ReachableGraspTripletArray.msg
  reachy_msgs/srv/GetReachability.srv
Labels: enhancement

#187 186 errors in discovery looked up ids
  reachy_utils/reachy_utils/discovery.py
Labels: bug, enhancement

#190 Fix arm motor range scan in discovery
  reachy_utils/reachy_utils/discovery.py
Labels: bug

#195 Reachy now spawns at the default position: 0, 0
  reachy_gazebo/launch/gazebo.launch.py
Labels: bug

#206 198 fix collision boxes com inertia and frictions in reachys urdf to make stuff graspable
  reachy_description/urdf/arm.urdf.xacro
Labels: bug
